name: Cmake Linux Build x86

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ cpplint

      - name: configure cmake
        run: cmake -S . -B build

      - name: build
        run: cmake --build build --parallel
